version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - '5000:5000'
    command: yarn start:watch
    env_file:
      - .env.local
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=database
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
volumes:
  mongodata:
